# Generated by Django 5.1.2 on 2024-12-22 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("arres_glosor", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Usert",
            new_name="User",
        ),
    ]
