# Generated by Django 5.1.2 on 2024-12-23 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arres_glosor", "0003_alter_user_groups_alter_user_user_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exercise_name", models.CharField(max_length=32)),
                ("time_last_edited", models.DateTimeField(auto_now_add=True)),
                ("formatted_time_last_edited", models.CharField(max_length=32)),
                ("translations", models.JSONField()),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
