# Generated by Django 5.1.2 on 2024-12-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arres_glosor", "0004_exercise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="translations",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
