# Generated by Django 5.1.2 on 2024-12-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arres_glosor", "0005_alter_exercise_translations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="time_last_edited",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
