# Generated by Django 5.1.2 on 2024-12-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arres_glosor", "0006_alter_exercise_time_last_edited"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="language1",
            field=models.CharField(default="default_value", max_length=32),
        ),
        migrations.AddField(
            model_name="exercise",
            name="language2",
            field=models.CharField(default="default_value", max_length=32),
        ),
    ]
